<?php

namespace RemovalBundle\Repository;

/**
 * BossdownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BossdownRepository extends \Doctrine\ORM\EntityRepository
{
}
