<?php

namespace RemovalBundle\Repository;

/**
 * MythiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MythiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
