<?php

namespace RemovalBundle\Repository;

/**
 * MythiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MythiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByFilter($filter, $objectif, $faction)
    {
        $qb = $this->createQueryBuilder('m')->where('m.skill = :skill')->andWhere('m.objectif = :objectif')->andWhere('m.faction = :faction');
        $qb->setParameter('skill', $filter);
        $qb->setParameter('objectif', $objectif);
        $qb->setParameter('faction', $faction);

        return $qb->getQuery()->getResult();
    }
}
