<?php

namespace RemovalBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
  public function myFindAll()
  {
    $qb = $this->createQueryBuilder('n');
    $qb->orderBy('n.dateNews', 'DESC');
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
