<?php

namespace RemovalBundle\Repository;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroupe($groupeID)
    {
        $qb = $this->createQueryBuilder('u')->leftJoin('u.groupe', 'g')->addSelect('g')->where('g.id = :id');
        $qb->setParameter('id', $groupeID);

        return $qb->getQuery()->getResult();
    }
}
