removal_homepage:
    path:     /
    defaults: { _controller: RemovalBundle:Home:read }

removal_news_read:
    path: /news/{newsUrl}
    defaults: {_controller: RemovalBundle:New:read }

removal_joueur_create:
    path:     /guilde/joueur/create
    defaults: { _controller: RemovalBundle:Joueur:create }

removal_joueur_read:
    path:     /guilde/joueur
    defaults: { _controller: RemovalBundle:Joueur:read }

removal_joueur_delete:
    path:     /guilde/joueur/delete/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:delete }

removal_joueur_update:
    path:     /guilde/joueur/update/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:update }

removal_joueur_read_all:
    path:     /guilde/joueur/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:readAll }


removal_participation_create:
    path:     /admin/participation/create
    defaults: { _controller: RemovalBundle:Participation:create }

removal_participation_read:
    path:     /admin/participation
    defaults: { _controller: RemovalBundle:Participation:read }

removal_participation_update:
    path:     /admin/participation/update/{participationID}
    defaults: { _controller: RemovalBundle:Participation:update }

removal_participation_delete:
    path:     /admin/participation/delete/{participationID}
    defaults: { _controller: RemovalBundle:Participation:delete }




removal_admin_read_all_users:
    path:     /admin/read/users
    defaults: { _controller: RemovalBundle:Admin:readAllUsers }

removal_admin_edit_user:
    path:     /admin/edit/{userID}
    defaults: { _controller: RemovalBundle:Admin:update }

removal_admin_delete_status:
    path:     /admin/delete
    defaults: { _controller: RemovalBundle:Admin:deleteAll }

removal_admin_delete_one_status:
    path:     /admin/delete/{statusID}
    defaults: { _controller: RemovalBundle:Admin:deleteOne }

removal_admin_confirm_one_status:
    path:     /admin/confirm/{statusID}
    defaults: { _controller: RemovalBundle:Admin:confirmationParticipation }




removal_gestion_read:
    path:     /guilde/gestion
    defaults: { _controller: RemovalBundle:Gestion:read }

removal_gestion_status:
    path:     /guilde/gestion/status/{participationID}
    defaults: { _controller: RemovalBundle:Gestion:validationStatus }

removal_gestion_status_create:
    path:     /admin/status/create
    defaults: { _controller: RemovalBundle:Admin:newStatus }



removal_hotel_read:
    path:     /admin/hotel
    defaults: { _controller: RemovalBundle:Api:returnApi }

removal_hotel_read_kaiserdh:
    path:     /admin/hotel/kaiserdh
    defaults: { _controller: RemovalBundle:Api:kaiserdh }




removal_roster_read:
    path:     /roster
    defaults: { _controller: RemovalBundle:Roster:read }

removal_candidature_read:
    path:     /sb/candidature
    defaults: { _controller: RemovalBundle:Candidature:read }

removal_candidature_create:
    path:     /candidature/create
    defaults: { _controller: RemovalBundle:Candidature:create }
