removal_homepage:
    path:     /
    defaults: { _controller: RemovalBundle:Home:read }

removal_moreNews:
    path: /moreNews/fn={fn}
    defaults: { _controller: RemovalBundle:New:more }

removal_news_read:
    path: /news/{newsUrl}
    defaults: {_controller: RemovalBundle:New:read }

removal_moreComment:
    path: /news/{newsUrl}/moreComments/fc={fc}
    defaults: { _controller: RemovalBundle:Comment:more }

removal_news_create:
    path: /news/create/
    defaults: { _controller: RemovalBundle:New:create }

removal_news_edit:
    path: /news/edit/{newsUrl}
    defaults: { _controller: RemovalBundle:New:edit }

removal_news_delete:
    path: /news/delete/{newsUrl}
    defaults: { _controller: RemovalBundle:New:delete }

removal_joueur_create:
    path:     /guilde/joueur/create
    defaults: { _controller: RemovalBundle:Joueur:create }

removal_joueur_read:
    path:     /guilde/joueur
    defaults: { _controller: RemovalBundle:Joueur:read }

removal_joueur_delete:
    path:     /guilde/joueur/delete/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:delete }

removal_joueur_update:
    path:     /guilde/joueur/update/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:update }

removal_joueur_read_all:
    path:     /guilde/joueur/{joueurID}
    defaults: { _controller: RemovalBundle:Joueur:readAll }


removal_participation_create:
    path:     /sb/participation/create
    defaults: { _controller: RemovalBundle:Participation:create }

removal_participation_read:
    path:     /sb/participation
    defaults: { _controller: RemovalBundle:Participation:read }

removal_participation_update:
    path:     /sb/participation/update/{participationID}
    defaults: { _controller: RemovalBundle:Participation:update }

removal_participation_delete:
    path:     /admin/participation/delete/{participationID}
    defaults: { _controller: RemovalBundle:Participation:delete }




removal_admin_read_all_users:
    path:     /admin/read/users
    defaults: { _controller: RemovalBundle:Admin:readAllUsers }

removal_admin_liste_membre:
    path:     /admin/membres
    defaults: { _controller: RemovalBundle:Admin:listeMembres }

removal_admin_edit_user:
    path:     /admin/edit/{userID}
    defaults: { _controller: RemovalBundle:Admin:update }

removal_admin_delete_status:
    path:     /admin/delete
    defaults: { _controller: RemovalBundle:Admin:deleteAll }

removal_admin_delete_one_status:
    path:     /admin/delete/{statusID}
    defaults: { _controller: RemovalBundle:Admin:deleteOne }

removal_admin_confirm_one_status:
    path:     /admin/confirm/{statusID}
    defaults: { _controller: RemovalBundle:Admin:confirmationParticipation }

removal_admin_create_recrutement:
    path:     /sb/recrutement/create
    defaults: { _controller: RemovalBundle:Recrutement:create }

removal_admin_read_recrutement:
    path:     /sb/recrutement
    defaults: { _controller: RemovalBundle:Recrutement:read }

removal_admin_update_recrutement:
    path:     /sb/recrutement/{recrutementID}
    defaults: { _controller: RemovalBundle:Recrutement:update }

removal_admin_delete_recrutement:
    path:     /sb/recrutement/delete/{recrutementID}
    defaults: { _controller: RemovalBundle:Recrutement:delete }




removal_gestion_read:
    path:     /guilde/gestion
    defaults: { _controller: RemovalBundle:Gestion:read }

removal_gestion_read_archive:
    path:     /guilde/gestion/archive
    defaults: { _controller: RemovalBundle:Gestion:readArchive }

removal_gestion_status:
    path:     /guilde/gestion/status/{participationID}
    defaults: { _controller: RemovalBundle:Gestion:validationStatus }

removal_gestion_status_create:
    path:     /admin/status/create
    defaults: { _controller: RemovalBundle:Admin:newStatus }

removal_gestion_status_create_sb:
    path:     /sb/status/create
    defaults: { _controller: RemovalBundle:Admin:newStatusSb }

removal_gestion_status_archive:
    path:     /guilde/status/archive/{participationID}
    defaults: { _controller: RemovalBundle:Gestion:archiverParticipation }



removal_hotel_read:
    path:     /admin/hotel
    defaults: { _controller: RemovalBundle:Api:returnApi }

removal_hotel_read_kaiserdh:
    path:     /admin/hotel/kaiserdh
    defaults: { _controller: RemovalBundle:Api:kaiserdh }




removal_roster_read:
    path:     /roster
    defaults: { _controller: RemovalBundle:Roster:read }

removal_candidature_read:
    path:     /sb/candidature
    defaults: { _controller: RemovalBundle:Candidature:read }

removal_candidature_read_archive:
    path:     /sb/candidature/archives
    defaults: { _controller: RemovalBundle:Candidature:readArchive }

removal_candidature_create:
    path:     /user/candidature/create
    defaults: { _controller: RemovalBundle:Candidature:create }

removal_candidature_update_status:
    path:     /sb/candidature/status/{candidatureID}
    defaults: { _controller: RemovalBundle:Candidature:update }

removal_sb_read:
    path:     /sb
    defaults: { _controller: RemovalBundle:Sb:read }


removal_sb_raid_read:
    path:     /sb/raid/read
    defaults: { _controller: RemovalBundle:Sb:readRaid }

removal_sb_raid_create:
    path:     /sb/raid/create
    defaults: { _controller: RemovalBundle:Sb:createRaid }

removal_sb_raid_update:
    path:     /sb/raid/update/{raidID}
    defaults: { _controller: RemovalBundle:Sb:updateRaid }

removal_sb_raid_delete:
    path:     /sb/raid/delete/{raidID}
    defaults: { _controller: RemovalBundle:Sb:deleteRaid }

removal_sb_boss_create:
    path:     /sb/boss/create
    defaults: { _controller: RemovalBundle:Sb:createBoss }

removal_sb_boss_read:
    path:     /sb/boss/read
    defaults: { _controller: RemovalBundle:Sb:readBoss }

removal_sb_boss_delete:
    path:     /sb/boss/delete/{bossID}
    defaults: { _controller: RemovalBundle:Sb:deleteBoss }

removal_sb_boss_update:
    path:     /sb/boss/update/{bossID}
    defaults: { _controller: RemovalBundle:Sb:updateBoss }



removal_user_groupe_create:
    path:     /mythique/create
    defaults: { _controller: RemovalBundle:Mythique:create }

removal_user_groupe_read:
    path:     /mythique
    defaults: { _controller: RemovalBundle:Mythique:read }

removal_user_groupe_inscription:
    path:     /mythique/inscription/{groupeID}
    defaults: { _controller: RemovalBundle:Mythique:inscription }

removal_user_groupe_update:
    path:     /mythique/update/{groupeID}
    defaults: { _controller: RemovalBundle:Mythique:update }

removal_user_groupe_delete:
    path:     /mythique/delete/{groupeID}
    defaults: { _controller: RemovalBundle:Mythique:delete }

removal_user_groupe_gestion:
    path:     /mythique/gestion
    defaults: { _controller: RemovalBundle:Mythique:gestionRead }
